import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';
import { MATH_GL_TYPES } from './math-gl-types.constant.js';

export interface IGenerateMathGLTypesOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLTypes({ name, length }: IGenerateMathGLTypesOptions): string {
  return [
    ...autoGeneratedFileComment(),
    ``,
    `export type ${name}<GType extends ArrayLike<number> = ArrayLike<number>> = Omit<GType, number | 'length'> & {`,
    `  readonly length: ${length};`,
    ...Array.from({ length }, (_, index) => {
      return `  [${index}]: number;`;
    }),
    `  [index: number]: number;`,
    `};`,
    ``,
    `export type readonly_${name}<GType extends ArrayLike<number> = ArrayLike<number>> = Readonly<${name}<GType>>;`,
    ``,
    ...MATH_GL_TYPES.flatMap(([type, array]) => {
      return [`export type ${name}_${type} = ${name}<${array}>;`];
    }),
    ``,
  ].join('\n');
}
