import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLSubtractOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLSubtract({ name, length }: IGenerateMathGLSubtractOptions): string {
  return [
    ...autoGeneratedFileComment(),
    `import { ${name}, readonly_${name} } from './${name}.type.js';`,
    ``,
    `/**`,
    ` * Subtract two ${name}'s (subtract \`b\` from \`a\`).`,
    ` */`,
    `export function ${name}_subtract<GType extends ArrayLike<number>>(`,
    `  out: ${name}<GType>,`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): ${name}<GType> {`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  out[${index}] = a[${index}] - b[${index}];`;
    }),
    `  return out;`,
    `}`,
    ``,
  ].join('\n');
}
