import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLVectorDotOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLVectorDot(
  {
    name,
    length,
  }: IGenerateMathGLVectorDotOptions,
): string {
  return [
    ...autoGeneratedFileComment(),
    `import { readonly_${name} } from './${name}.type';`,
    ``,
    `/**`,
    ` * Calculates the dot product of two ${name}'s.`,
    ` */`,
    `export function ${name}_dot(`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): number {`,
    `  return (`,
    ...Array.from({ length }, (_, index: number): string => {
      return `    ${index > 0 ? '+ ' : '  '}a[${index}] * b[${index}]`;
    }),
    `  );`,
    `}`,
    ``,
  ].join('\n');
}


