import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLVectorSquaredDistanceOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGlVectorSquaredDistance({
  name,
  length,
}: IGenerateMathGLVectorSquaredDistanceOptions): string {
  const values: readonly string[] = ['x', 'y', 'z', 'w'];

  return [
    ...autoGeneratedFileComment(),
    `import { readonly_${name} } from './${name}.type.js';`,
    ``,
    `/**`,
    ` * Calculates the squared euclidian distance between two ${name}'s.`,
    ` */`,
    `export function ${name}_squared_distance(`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): number {`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  const ${values[index]}: number = b[${index}] - a[${index}];`;
    }),
    `  return (`,
    ...Array.from({ length }, (_, index: number): string => {
      return `    ${index > 0 ? '+ ' : '  '}${values[index]} * ${values[index]}`;
    }),
    `  );`,
    `}`,
    ``,
  ].join('\n');
}
