import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLAddOptions {
  name: string;
  length: number;
}

export function generateMathGLAdd(
  {
    name,
    length,
  }: IGenerateMathGLAddOptions,
): string {
  return [
    ...autoGeneratedFileComment(),
    `import { ${name}, readonly_${name} } from './${name}.type';`,
    ``,
    `/**`,
    ` * Adds two ${name}'s.`,
    ` */`,
    `export function ${name}_add<GType extends ArrayLike<number>>(`,
    `  out: ${name}<GType>,`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): ${name}<GType> {`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  out[${index}] = a[${index}] + b[${index}];`;
    }),
    `  return out;`,
    `}`,
    ``,
  ].join('\n');
}


