import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLFromValuesAlias {
  readonly name: string;
}

export function generateMathGLFromValuesAlias(
  {
    name,
  }: IGenerateMathGLFromValuesAlias,
): string {
  return [
    ...autoGeneratedFileComment(),
    `export { ${name}_from_values as $${name} } from './${name}_from_values';`,
    ``,
  ].join('\n');
}
