import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLFromValuesAlias {
  readonly name: string;
}

export function generateMathGLFromValuesAlias({ name }: IGenerateMathGLFromValuesAlias): string {
  return [
    ...autoGeneratedFileComment(),
    `export { ${name}_from_values as $${name} } from './${name}_from_values.js';`,
    ``,
  ].join('\n');
}
