import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLEqualsOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLEquals(
  {
    name,
    length,
  }: IGenerateMathGLEqualsOptions,
): string {
  return [
    ...autoGeneratedFileComment(),
    `import { readonly_${name} } from './${name}.type';`,
    ``,
    `/**`,
    ` *  Returns whether or not the ${name}'s have exactly the same elements in the same position.`,
    ` */`,
    `export function ${name}_equals(`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): boolean {`,
    `  return (`,
    ...Array.from({ length }, (_, index: number): string => {
      return `    ${index > 0 ? '&& ' : '   '}(a[${index}] === b[${index}])`;
    }),
    `  );`,
    `}`,
    ``,
  ].join('\n');
}


