import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLCopyOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLCopy(
  {
    name,
    length,
  }: IGenerateMathGLCopyOptions,
): string {
  return [
    ...autoGeneratedFileComment(),
    `import { ${name}, readonly_${name} } from './${name}.type';`,
    ``,
    `export function ${name}_copy<GType extends ArrayLike<number>>(`,
    `  out: ${name}<GType>,`,
    `  a: readonly_${name},`,
    `): ${name}<GType> {`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  out[${index}] = a[${index}];`;
    }),
    `  return out;`,
    `}`,
    ``,
  ].join('\n');
}


