import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLVectorNegateOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLVectorNegate(
  {
    name,
    length,
  }: IGenerateMathGLVectorNegateOptions,
): string {
  return [
    ...autoGeneratedFileComment(),
    `import { ${name}, readonly_${name} } from './${name}.type';`,
    ``,
    `export function ${name}_negate<GType extends ArrayLike<number>>(`,
    `  out: ${name}<GType>,`,
    `  a: readonly_${name},`,
    `): ${name}<GType> {`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  out[${index}] = -a[${index}];`;
    }),
    `  return out;`,
    `}`,
    ``,
  ].join('\n');
}


