import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLVectorLengthOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLVectorLength({
  name,
  length,
}: IGenerateMathGLVectorLengthOptions): string {
  return [
    ...autoGeneratedFileComment(),
    `import { readonly_${name} } from './${name}.type.js';`,
    `import { math_hypot } from '../../others/math_hypot.js';`,
    ``,
    `/**`,
    ` * Calculates the length of a ${name}.`,
    ` */`,
    `export function ${name}_length(`,
    `  a: readonly_${name},`,
    `): number {`,
    `  return math_hypot(`,
    ...Array.from({ length }, (_, index: number): string => {
      return `    a[${index}],`;
    }),
    `  );`,
    `}`,
    ``,
  ].join('\n');
}
