import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLVectorAngleOptions {
  readonly name: string;
}

export function generateMathGLVectorAngle({ name }: IGenerateMathGLVectorAngleOptions): string {
  return [
    ...autoGeneratedFileComment(),
    `import { readonly_${name} } from './${name}.type.js';`,
    `import { ${name}_dot } from './${name}_dot.js';`,
    `import { ${name}_squared_length } from './${name}_squared_length.js';`,
    `import { math_sqrt } from '../../others/math_sqrt.js';`,
    `import { math_acos } from '../../others/math_acos.js';`,
    `import { math_min } from '../../others/math_min.js';`,
    `import { math_max } from '../../others/math_max.js';`,
    ``,
    `/**`,
    ` * Returns the angle between two ${name}'s.`,
    ` */`,
    `export function ${name}_angle(`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): number {`,
    `  const mag: number = math_sqrt(${name}_squared_length(a) * ${name}_squared_length(b));`,
    `  const cosine: number = mag && ${name}_dot(a, b) / mag;`,
    `  return math_acos(math_min(math_max(cosine, -1), 1));`,
    `}`,
    ``,
  ].join('\n');
}
