import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLVectorDistanceOptions {
  readonly name: string;
}

export function generateMathGlVectorDistance({
  name,
}: IGenerateMathGLVectorDistanceOptions): string {
  return [
    ...autoGeneratedFileComment(),
    `import { readonly_${name} } from './${name}.type.js';`,
    `import { ${name}_squared_distance } from './${name}_squared_distance.js';`,
    `import { math_sqrt } from '../../others/math_sqrt.js';`,
    ``,
    `/**`,
    ` * Calculates the euclidian distance between two ${name}'s.`,
    ` */`,
    `export function ${name}_distance(`,
    `  a: readonly_${name},`,
    `  b: readonly_${name},`,
    `): number {`,
    `  return math_sqrt(${name}_squared_distance(a, b));`,
    `}`,
    ``,
  ].join('\n');
}
