import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment.js';

export interface IGenerateMathGLVectorInverseOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLVectorInverse({
  name,
  length,
}: IGenerateMathGLVectorInverseOptions): string {
  return [
    ...autoGeneratedFileComment(),
    `import { ${name}, readonly_${name} } from './${name}.type.js';`,
    ``,
    `/**`,
    ` * Returns the inverse of the components of a  ${name}.`,
    ` */`,
    `export function ${name}_inverse<GType extends ArrayLike<number>>(`,
    `  out: ${name}<GType>,`,
    `  a: readonly_${name},`,
    `): ${name}<GType> {`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  out[${index}] = 1 / a[${index}];`;
    }),
    `  return out;`,
    `}`,
    ``,
  ].join('\n');
}
