import { autoGeneratedFileComment } from '../../misc/auto-generated-file-comment';

export interface IGenerateMathGLVectorNormalizeOptions {
  readonly name: string;
  readonly length: number;
}

export function generateMathGLVectorNormalize(
  {
    name,
    length,
  }: IGenerateMathGLVectorNormalizeOptions,
): string {
  return [
    ...autoGeneratedFileComment(),
    `import { ${name}, readonly_${name} } from './${name}.type';`,
    `import { ${name}_length } from './${name}_length';`,
    ``,
    `export function ${name}_normalize<GType extends ArrayLike<number>>(`,
    `  out: ${name}<GType>,`,
    `  a: readonly_${name},`,
    `): ${name}<GType> {`,
    `  let length: number = ${name}_length(a);`,
    `  if (length > 0) {`,
    `    length = 1 / length;`,
    `  }`,
    ...Array.from({ length }, (_, index: number): string => {
      return `  out[${index}] = a[${index}] * length;`;
    }),
    `  return out;`,
    `}`,
    ``,
  ].join('\n');
}
